%%{init: {"flowchart": {"defaultRenderer": "elk"}}}%%
graph LR
  TAX["Causal Taxonomy\nconfig_taxonomy.json"]
  CTG["Causal Types (14)"]
  TAX --> CTG

  D_PEN["Penal"]
  D_CIV["Civil"]
  D_AMM["Administrative"]
  D_MIX["Mixed"]

  CTG --> D_PEN
  CTG --> D_CIV
  CTG --> D_AMM
  CTG --> D_MIX

  PEN_FACTUAL["PEN_FACTUAL\nCore:1 Acc:2 Att:9"]
  PEN_INTERVENING["PEN_INTERVENING\nCore:1 Acc:4 Att:4"]
  IMPUTATION_FILTER["IMPUTATION_FILTER\nCore:1 Acc:3 Att:3"]
  PEN_PROPERTY_QUALIFICATION["PEN_PROPERTY_QUALIFICATION\nCore:2 Acc:4 Att:5"]
  PEN_RIGHTS_BALANCING["PEN_RIGHTS_BALANCING\nCore:2 Acc:3 Att:5"]
  PEN_COLPA_GRADATION["PEN_COLPA_GRADATION\nCore:2 Acc:6 Att:5"]

  D_PEN --> PEN_FACTUAL
  D_PEN --> PEN_INTERVENING
  D_PEN --> IMPUTATION_FILTER
  D_PEN --> PEN_PROPERTY_QUALIFICATION
  D_PEN --> PEN_RIGHTS_BALANCING
  D_PEN --> PEN_COLPA_GRADATION

  CIV_REMOTENESS["CIV_REMOTENESS\nCore:2 Acc:3 Att:5"]
  CIV_CONTRACT_REMEDIES["CIV_CONTRACT_REMEDIES\nCore:2 Acc:6 Att:5"]
  CIV_SALE_DEFECTS["CIV_SALE_DEFECTS\nCore:2 Acc:2 Att:5"]
  CIV_CUSTODY_DAMAGE["CIV_CUSTODY_DAMAGE\nCore:2 Acc:2 Att:5"]

  D_CIV --> CIV_REMOTENESS
  D_CIV --> CIV_CONTRACT_REMEDIES
  D_CIV --> CIV_SALE_DEFECTS
  D_CIV --> CIV_CUSTODY_DAMAGE

  AMM_PROCEDURAL_LEGITIMACY["AMM_PROCEDURAL_LEGITIMACY\nCore:3 Acc:4 Att:5"]
  AMM_AUTOTUTELA_BALANCE["AMM_AUTOTUTELA_BALANCE\nCore:2 Acc:3 Att:5"]
  AMM_DELAY_REMEDIES["AMM_DELAY_REMEDIES\nCore:2 Acc:2 Att:5"]

  D_AMM --> AMM_PROCEDURAL_LEGITIMACY
  D_AMM --> AMM_AUTOTUTELA_BALANCE
  D_AMM --> AMM_DELAY_REMEDIES

  MIXED_PEN_CIV_CONCURRENCE["MIXED_PEN_CIV_CONCURRENCE\nCore:3 Acc:2 Att:5"]
  D_MIX --> MIXED_PEN_CIV_CONCURRENCE

  T_CONDIZIONALISTICA["T_CONDIZIONALISTICA"]
  T_SCI_PROB["T_SCI_PROB"]
  T_REGOLARITA["T_REGOLARITA"]
  T_INTERRUPTION_41_2["T_INTERRUPTION_41_2"]
  T_FORTUITO["T_FORTUITO"]
  T_CIV_FILTERS["T_CIV_FILTERS"]
  T_CIV_REMEDIES["T_CIV_REMEDIES"]
  T_CIV_GARANZIA_VIZI["T_CIV_GARANZIA_VIZI"]
  T_CIV_CUSTODIA["T_CIV_CUSTODIA"]
  T_PEN_PATRIMONIALI["T_PEN_PATRIMONIALI"]
  T_PEN_DIRITTI_BILANCIAMENTO["T_PEN_DIRITTI_BILANCIAMENTO"]
  T_PEN_COLPA_GRADAZIONE["T_PEN_COLPA_GRADAZIONE"]
  T_AMM_GARANZIE["T_AMM_GARANZIE"]
  T_AMM_AUTOTUTELA["T_AMM_AUTOTUTELA"]
  T_AMM_RITARDO["T_AMM_RITARDO"]
  T_MIXED_CONCORSO_TUTELE["T_MIXED_CONCORSO_TUTELE"]

  PEN_FACTUAL --> T_CONDIZIONALISTICA
  PEN_FACTUAL --> T_SCI_PROB
  PEN_FACTUAL --> T_REGOLARITA
  PEN_INTERVENING --> T_CONDIZIONALISTICA
  PEN_INTERVENING --> T_REGOLARITA
  PEN_INTERVENING --> T_INTERRUPTION_41_2
  IMPUTATION_FILTER --> T_FORTUITO
  PEN_PROPERTY_QUALIFICATION --> T_PEN_PATRIMONIALI
  PEN_RIGHTS_BALANCING --> T_PEN_DIRITTI_BILANCIAMENTO
  PEN_COLPA_GRADATION --> T_PEN_COLPA_GRADAZIONE
  CIV_REMOTENESS --> T_REGOLARITA
  CIV_REMOTENESS --> T_CIV_FILTERS
  CIV_CONTRACT_REMEDIES --> T_CIV_REMEDIES
  CIV_SALE_DEFECTS --> T_CIV_GARANZIA_VIZI
  CIV_CUSTODY_DAMAGE --> T_CIV_CUSTODIA
  AMM_PROCEDURAL_LEGITIMACY --> T_AMM_GARANZIE
  AMM_AUTOTUTELA_BALANCE --> T_AMM_AUTOTUTELA
  AMM_DELAY_REMEDIES --> T_AMM_RITARDO
  MIXED_PEN_CIV_CONCURRENCE --> T_MIXED_CONCORSO_TUTELE

  classDef pen fill:#fde68a,stroke:#b45309,color:#111827;
  classDef civ fill:#bfdbfe,stroke:#1d4ed8,color:#111827;
  classDef amm fill:#bbf7d0,stroke:#15803d,color:#111827;
  classDef mix fill:#fbcfe8,stroke:#be185d,color:#111827;
  classDef theory fill:#e5e7eb,stroke:#374151,color:#111827;

  class PEN_FACTUAL pen;
  class PEN_INTERVENING pen;
  class IMPUTATION_FILTER pen;
  class PEN_PROPERTY_QUALIFICATION pen;
  class PEN_RIGHTS_BALANCING pen;
  class PEN_COLPA_GRADATION pen;
  class CIV_REMOTENESS civ;
  class CIV_CONTRACT_REMEDIES civ;
  class CIV_SALE_DEFECTS civ;
  class CIV_CUSTODY_DAMAGE civ;
  class AMM_PROCEDURAL_LEGITIMACY amm;
  class AMM_AUTOTUTELA_BALANCE amm;
  class AMM_DELAY_REMEDIES amm;
  class MIXED_PEN_CIV_CONCURRENCE mix;
  class T_CONDIZIONALISTICA theory;
  class T_SCI_PROB theory;
  class T_REGOLARITA theory;
  class T_INTERRUPTION_41_2 theory;
  class T_FORTUITO theory;
  class T_CIV_FILTERS theory;
  class T_CIV_REMEDIES theory;
  class T_CIV_GARANZIA_VIZI theory;
  class T_CIV_CUSTODIA theory;
  class T_PEN_PATRIMONIALI theory;
  class T_PEN_DIRITTI_BILANCIAMENTO theory;
  class T_PEN_COLPA_GRADAZIONE theory;
  class T_AMM_GARANZIE theory;
  class T_AMM_AUTOTUTELA theory;
  class T_AMM_RITARDO theory;
  class T_MIXED_CONCORSO_TUTELE theory;
